### PR TITLE
fix: various bugfixes

### PR DESCRIPTION
**Pull request by timini**
- added gitlab and ssh credentials
- fixed some bugs with LSFPlatform compute env
- added improved handling of 409 already created for adding members to workspaces
- couple of small fixes to docs

acceptance tests passing: 

```
#( 02/03/24@ 8:39am )( timrichardson@GEL-CJ74D2X9MF ):~/projects/terraform-provider-nftower@bugfix-various✗✗✗
   make                                                                                           
TF_ACC=1 go test ./... -v  -timeout 120m
?   	github.com/healx/terraform-provider-nftower	[no test files]
?   	github.com/healx/terraform-provider-nftower/internal/client	[no test files]
?   	github.com/healx/terraform-provider-nftower/internal/template	[no test files]
=== RUN   TestAccDataSourceCredentialsAWS
--- PASS: TestAccDataSourceCredentialsAWS (2.67s)
=== RUN   TestAccDataSourceCredentialsGithub
--- PASS: TestAccDataSourceCredentialsGithub (2.78s)
=== RUN   TestAccDataSourceCredentialsGitlab
--- PASS: TestAccDataSourceCredentialsGitlab (2.52s)
=== RUN   TestAccDataSourceOrganizationMember
--- PASS: TestAccDataSourceOrganizationMember (2.15s)
=== RUN   TestAccDataSourceWorkspaceParticipant
--- PASS: TestAccDataSourceWorkspaceParticipant (2.36s)
=== RUN   TestAccDataSourceWorkspace
--- PASS: TestAccDataSourceWorkspace (2.22s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestAccResourceComputeEnvironmentAWS
    resource_compute_environment_test.go:15: requires real AWS credentials
--- SKIP: TestAccResourceComputeEnvironmentAWS (0.00s)
=== RUN   TestAccResourceComputeEnvironmentLSF
    resource_compute_environment_test.go:82: requires real ssh login node
--- SKIP: TestAccResourceComputeEnvironmentLSF (0.00s)
=== RUN   TestFlattenEnvironmentVariables
--- PASS: TestFlattenEnvironmentVariables (0.00s)
=== RUN   TestFlattenComputeEnvironmentAWSBatchMinimal
--- PASS: TestFlattenComputeEnvironmentAWSBatchMinimal (0.00s)
=== RUN   TestFlattenComputeEnvironmentAWSBatchComplete
--- PASS: TestFlattenComputeEnvironmentAWSBatchComplete (0.00s)
=== RUN   TestFlattenComputeEnvironmentLSFPlatfromMinimal
--- PASS: TestFlattenComputeEnvironmentLSFPlatfromMinimal (0.00s)
=== RUN   TestFlattenComputeEnvironmentLSFPlatformComplete
--- PASS: TestFlattenComputeEnvironmentLSFPlatformComplete (0.00s)
=== RUN   TestAccResourceCredentialsAWS
--- PASS: TestAccResourceCredentialsAWS (2.22s)
=== RUN   TestAccResourceCredentialsGithub
--- PASS: TestAccResourceCredentialsGithub (2.24s)
=== RUN   TestAccResourceCredentialsGitlab
--- PASS: TestAccResourceCredentialsGitlab (2.27s)
=== RUN   TestAccResourceCredentialsSSH
--- PASS: TestAccResourceCredentialsSSH (2.21s)
=== RUN   TestAccResourceCredentials_basic
--- PASS: TestAccResourceCredentials_basic (2.32s)
=== RUN   TestAccResourceDataset_basic
--- PASS: TestAccResourceDataset_basic (2.02s)
=== RUN   TestAccResourceDatasetVersion_csv
--- PASS: TestAccResourceDatasetVersion_csv (2.32s)
=== RUN   TestAccResourceDatasetVersion_tsv
--- PASS: TestAccResourceDatasetVersion_tsv (2.21s)
=== RUN   TestAccResourceOrganizationMember
--- PASS: TestAccResourceOrganizationMember (1.92s)
=== RUN   TestAccResourceOrganizationMemberOwner
--- PASS: TestAccResourceOrganizationMemberOwner (3.72s)
=== RUN   TestAccResourceOrganizationMemberUpdateRole
--- PASS: TestAccResourceOrganizationMemberUpdateRole (5.41s)
=== RUN   TestAccResourcePipelineSecrets
--- PASS: TestAccResourcePipelineSecrets (2.32s)
=== RUN   TestAccResourceToken
--- PASS: TestAccResourceToken (1.72s)
=== RUN   TestAccResourceWorkspaceParticipant_basic
--- PASS: TestAccResourceWorkspaceParticipant_basic (2.21s)
=== RUN   TestAccResourceWorkspaceParticipant_email
--- PASS: TestAccResourceWorkspaceParticipant_email (2.19s)
=== RUN   TestAccResourceWorkspaceParticipant_maintain
--- PASS: TestAccResourceWorkspaceParticipant_maintain (2.10s)
=== RUN   TestAccResourceWorkspaceParticipant_updateRole
--- PASS: TestAccResourceWorkspaceParticipant_updateRole (4.25s)
=== RUN   TestAccResourceWorkspace
--- PASS: TestAccResourceWorkspace (1.88s)
PASS
ok  	github.com/healx/terraform-provider-nftower/internal/provider	60.672s
```

### CODE REVIEW

**Comment by timini** [comment]
@gareth-rogers-healx can i get a review for this please?

**Comment by timini** [comment]
@andyroyle @alexhermida anyone free for a review please?

**Comment by timini** [comment]
🙏

**Comment by gareth-rogers-healx** [comment]
Sorry @timini dropped off too far down my inbox. I'll have a look now.

**Review by gareth-rogers-healx — APPROVED** [review]
Looks good, thanks for fixing the tests

**Review by alexhermida — APPROVED** [review]
👍🏽  Thanks for the contribution @timini

**Pull request merged**
