### PR TITLE
feat: adding lsf-platform to compute envs

### PR DESCRIPTION
**Pull request by timini**
This PR adds support for IBM LSF compute envs

### CODE REVIEW

**Comment by alexhermida** [comment]
Hey @timini ! Thanks for the contribution 🙂  would be great if you can add at least one test [here](https://github.com/healx/terraform-provider-nftower/blob/main/internal/provider/resource_compute_environment_test.go) for the compute environment.
Thank you again!

**Comment by timini** [comment]
Sorry, couldn't find the test suite, will add.

**Comment by alexhermida** [comment]
> Sorry, couldn't find the test suite, will add.

No problem! The repo it's not great documented for external contributors, something to work on😄

**Comment by alexhermida** [comment]
Hi @timini you need to run locally `go generate ./...` and commit the changes with the new docs. 
As I said the `README.md` needs to be updated for contributors 😄 

Thaanks!

**Comment by timini** [comment]
@alexhermida can you kick off the tests again please?

**Comment by timini** [comment]
hi @alexhermida I'm interested in adding secrets support as a separate MR (sorry couldn't find a way to open an issue for discussion). How would i go about testing it locally, does it have to be done against a live instance of tower?

**Comment by alexhermida** [comment]
> in adding secrets support as a separate MR (sorry could

What do you mean adding secrets support? As it's right know already requires NFTOWER_API_KEY. I think the only test we currently have around that is to test if it's required.

If it's ok. I'll merge this and feel free to open a new MR with the code, we can discuss there if it's appropiate, probably is easier with the code 😄 

Thanks!

**Review by alexhermida — APPROVED** [review]

**Pull request merged**
